import { FormEvent, useEffect, useState } from "react";
import Loading from "../components/Loading";
import Navbar from "../components/Navbar";
import { deleteAccount, getCurrentUser, getSavedDestinations, logout, removeSavedDestination, updateProfile } from "../services/authApi";
import type { Destination, User } from "../types";

export default function Profile() {
  const [user, setUser] = useState<User | null>(null);
  const [saved, setSaved] = useState<Destination[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const load = () => { setError(null); void Promise.all([getCurrentUser(), getSavedDestinations()]).then(([profile, destinations]) => { setUser(profile); setSaved(destinations); }).catch((requestError: unknown) => setError(requestError instanceof Error ? requestError.message : "Unable to load profile.")); };
  useEffect(load, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); try { const updated = await updateProfile({ firstName: String(form.get("firstName")), lastName: String(form.get("lastName")) || null, phone: String(form.get("phone")) || null, city: String(form.get("city")) || null, country: String(form.get("country")) || null, languagePref: String(form.get("languagePref")) || null, preferences: { travelStyle: String(form.get("travelStyle")) || "" } }); setUser(updated); setNotice("Profile saved."); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to save profile."); } finally { setSaving(false); } }
  async function remove(city: Destination) { try { await removeSavedDestination(city.id); setSaved((current) => current.filter((item) => item.id !== city.id)); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to remove saved destination."); } }
  async function removeAccount() { if (!window.confirm("Delete your account and every trip? This cannot be undone.")) return; try { await deleteAccount(); logout(); window.location.hash = "#dashboard"; } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to delete account."); } }
  return <main className="workspace-page"><Navbar /><section className="workspace-hero shell"><div><p className="eyebrow">YOUR SETTINGS</p><h1>Profile</h1><p>Update your details, preferences, and saved places.</p></div></section>{error ? <p className="shell form-error">{error}</p> : !user ? <Loading label="Loading profile..." /> : <><form className="workspace-form shell" onSubmit={submit}><div className="form-row"><label>First name<input name="firstName" defaultValue={user.firstName} required /></label><label>Last name<input name="lastName" defaultValue={user.lastName ?? ""} /></label></div><label>Email address<input value={user.email} disabled /></label><div className="form-row"><label>Phone<input name="phone" defaultValue={user.phone ?? ""} /></label><label>Language<select name="languagePref" defaultValue={user.languagePref ?? "en"}><option value="en">English</option><option value="fr">French</option><option value="es">Spanish</option><option value="ja">Japanese</option></select></label></div><div className="form-row"><label>City<input name="city" defaultValue={user.city ?? ""} /></label><label>Country<input name="country" defaultValue={user.country ?? ""} /></label></div><label>Travel preference<select name="travelStyle" defaultValue={String(user.preferences.travelStyle ?? "")}><option value="">Choose a style</option><option value="culture">Culture</option><option value="nature">Nature</option><option value="food">Food</option><option value="adventure">Adventure</option><option value="relaxation">Relaxation</option></select></label>{notice && <p className="page-notice">{notice}</p>}<div className="form-actions"><button className="workspace-primary" disabled={saving}>{saving ? "Saving..." : "Save profile"}</button><button className="danger-button" type="button" onClick={() => void removeAccount()}>Delete account</button></div></form><section className="shell saved-destinations"><h2>Saved destinations</h2>{saved.length ? saved.map((city) => <div key={city.id}><span>{city.name}, {city.country}</span><button onClick={() => void remove(city)}>Remove</button></div>) : <p className="empty-copy">Save destinations to keep them here.</p>}</section></>}</main>;
}
